### ISSUE TITLE
Checkboxes to the left, in a column, instead of ragged right

### ISSUE THREAD

**Issue by grahamperrin** [QWERTYUIOPYOZO/ReFont#2]
Enhancement request. 

Where there's a list of fonts such as this: 

![2018-03-23 23 03 12](https://user-images.githubusercontent.com/192271/37857248-7b7e5d12-2ef1-11e8-84a5-8a70b09c5d56.png)

– it'll be easier to check multiple items if the boxes are in a column. 

(Negating the need to move the pointer horizontally whilst also moving it down or up.)

Thanks

**Comment by QWERTYUIOPYOZO** [comment]
Yes, easily fixable. I will do so for the next version.
Good to see you using the prerelease version.
